### ISSUE TITLE
Privacy badger under browser plugins

### ISSUE THREAD

**Issue by equinoxmatt** [privacytoolsIO/www.privacytools.io#73]
Hello,

I wondered why privacy badger is not on the recommended list of browser privacy plugins?

Many Thanks

**Comment by privacytoolsIO** [comment]
We're currently recommending Disconnect, and it's doing the same thing as privacy badger. We don't want to recommend two tools that does the exact same thing.

**Comment by Shifterovich** [comment]
Phrase "Disconnect or Privacy Badger" would work.

**Comment by equinoxmatt** [comment]
Yeah.  I get where you are coming from.  However Privacy Badger is funded by the EFF?  This gives it added legitimacy.  Since you have HTTPS ANYWHERE as a recommendation,  Privacy Badger being listed makes sense.  I would be happy with "Disconnect or Privacy Badger".

**Comment by privacytoolsIO** [comment]
For now I've added Privacy Badger as an alternative within the description: https://www.privacytools.io/#addons

**Comment by PrivacyDefender** [comment]
EFF's Privacy Badger uses heuristic blocking and expands its own local blacklist by learning the user's behavior and recognizing ads/tracker, while Disconnect uses predefined blocklists which are extended remotely.
Additionally, as far as I know, Disconnect's blocklists are available in uBlock Origin and since Firefox 43 also in FireFox (private mode), so I can't see why one has to install Disconnect AND uBlock Origin, resp. Disconnect instead of Privacy Badger.

**Comment by Shifterovich** [comment]
@PrivacyDefender And uBlock is mentioned right below Disconnect. I suggest recommending Privacy Badger instead of Disconnect.

**Comment by privacytoolsIO** [comment]
Disconnect and Privacy Badger was removed today. Since uBlock is doing the exact same thing already.

**Comment by Shifterovich** [comment]
@privacytoolsIO Well, Disconnect does the same thing, but Privacy Badger does not. Unlike Disconnect, which is supplied with a **blacklist**, Privacy Badger **learns** what third party resources may be tracking you.
